
<div id="left-menu">
              <div class="sub-left-menu scroll">
                <ul class="nav nav-list">
                    <li><div class="left-bg"></div></li>
                    <li class="time">
                      <h1 class="animated fadeInLeft">21:00</h1>
                      <p class="animated fadeInRight">Sat,October 1st 2029</p>
                    </li>
                    <li class="active ripple">
                      <a class="tree-toggle nav-header"><span class="fa-home fa"></span> Documentos
                        <span class="fa-angle-right fa right-arrow text-right"></span>
                      </a>
                      <ul class="nav nav-list tree">
                          <li><a href="#">Cria Documento</a></li>
                          <li><a href="#">Listar Documento</a></li>
                          <li><a href="#">Documentos Partilhado</a></li>
                      </ul>
                    </li>
                    <li class="ripple">
                      <a class="tree-toggle nav-header">
                        <span class="fa-diamond fa"></span> Definição
                        <span class="fa-angle-right fa right-arrow text-right"></span>
                      </a>
                      <ul class="nav nav-list tree">
                        <li><a href="#">Top Navigation</a></li>
                        <li><a href="#">Boxed</a></li>
                      </ul>
                    </li>



                    <li class="ripple"><a class="tree-toggle nav-header"><span class="fa fa-envelope-o"></span> Notificação <span class="fa-angle-right fa right-arrow text-right"></span> </a>
                      <ul class="nav nav-list tree">
                        <li><a href="#">Inbox</a></li>
                        <li><a href="#">Compose Mail</a></li>
                        <li><a href="#">View Mail</a></li>
                      </ul>
                    </li>
                  </ul>


                </div>
            </div>

<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

