

<!DOCTYPE html>
<html lang="en" ng-app="pdc_app">
<head>
  
  <meta charset="utf-8">
  <meta name="keyword" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cadastro do utilizador</title>
 
    <!-- start: Css -->
    <link rel="stylesheet" type="text/css" href="././publico/asset/css/bootstrap.min.css">
<!--   <link rel="stylesheet" type="text/css" href="asset/css/plugins/font-awesome.min.css"/>-->
  <link rel="stylesheet" type="text/css" href="././publico/asset/css/plugins/simple-line-icons.css"/>
   <link rel="stylesheet" type="text/css" href="././publico/asset/css/plugins/animate.min.css"/>
      
  <link href="././publico/asset/css/style.css" rel="stylesheet">
  <!-- end: Css -->
  
    <script src="././bower_components/angular/angular.min.js"></script>
<!--       <script src="././bower_components/angular-route/angular-route.min.js"></script>-->
       <script src="app\app_js\ManController.js"></script>
  <link rel="shortcut icon" href="asset/img/logomi.png">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

 <body id="mimin" class="dashboard boxed container padding-0">
      <!-- start: Header -->
        <nav class="navbar container navbar-default header navbar-fixed-top">
          <div class="col-md-12 nav-wrapper">
            <div class="navbar-header" style="width:100%;">
              <div class="opener-left-menu is-open">
                <span class="top"></span>
                <span class="middle"> </span>
                <span class="bottom"></span>
              </div>
                <a href="index" class="navbar-brand"> 
                 <b>PDC DOCS</b>
                </a>

          </div>
        </nav>
      <!-- end: Header -->

      <div class="container-fluid mimin-wrapper bg-light-grey">
  
         
            <div id="content">


                <div class="col-md-12" style="padding:20px;">
                    <div class="col-md-12 padding-0">
                        <div class="col-md-8 padding-0">
                            


                            <div class="col-md-12">
                                <div class="panel box-v4">
                                    <div class="panel-heading bg-white border-none">
                          <h4><span class="icon-notebook icons"></span> Cadastro do Utilizador </h4>
                                </div>

                  
                  <div class="col-md-12 panel">
                    
                    <div class="col-md-12 panel-body" style="padding-bottom:30px;">
                      <div class="col-md-12">
                          
                          <form class="cmxform" id="signupForm"   method="POST" action="cadastro" >
                              
                          <div class="col-md-6">
                              
                            <div class="form-group form-animate-text" style="margin-top:40px !important;">
                              <input type="text" class="form-text" id="validate_firstname" name="username" ng-model="nome"required>
                              <span class="bar"></span>
                              <label>Nome completo</label>
                            </div>
                                              
<!--                            <div class="form-group form-animate-text" style="margin-top:40px !important;">
                              <input type="text" class="form-text" id="validate_lastname" name="validate_lastname" required>
                              <span class="bar"></span>
                              <label>Lastname</label>
                            </div>-->

                            <div class="form-group form-animate-text" style="margin-top:40px !important;">
                                <input type="text" class="form-text" id="validate_username" name="validate_username" required>
                              <span class="bar"></span>
                              <label>Nome do Utilizador</label>
                            </div>
                          </div>

                          <div class="col-md-6">
<!--                            <div class="form-group form-animate-text" style="margin-top:40px !important;">
                              <input type="password" class="form-text" id="validate_password" name="validate_password"  required>
                              <span class="bar"></span>
                              <label>Password</label>
                            </div>

                            <div class="form-group form-animate-text" style="margin-top:40px !important;">
                              <input type="password" class="form-text" id="validate_confirm_password" name="validate_confirm_password" required>
                              <span class="bar"></span>
                              <label>Confirma Password</label>
                            </div>-->

                            <div class="form-group form-animate-text" style="margin-top:40px !important;">
                                <input type="text" class="form-text" id="validate_email" name="validate_email"  required>
                              <span class="bar"></span>
                              <label>Email</label>
                            </div>
                          </div>                   
                          <div class="col-md-12">
                              <div class="form-group form-animate-checkbox">
                                  <input type="checkbox" class="checkbox"  id="validate_agree" name="validate_agree">
                                  <label>Aceita os termos de privacidade</label>  
                              </div>
                              <input class="submit btn btn-danger" type="submit" value="Submit" >
                        </div>
                           
                            <p>
                          
                      </form>

                    </div>
                  </div>
                </div>
            

         </div> 
    </div>
  </div>
                        
    </div>

                 
                   
                </div>
            </div>
          <!-- end: content -->

      </div>

      <!-- start: Mobile -->
      
      <button id="mimin-mobile-menu-opener" class="animated rubberBand btn btn-circle btn-danger">
        <span class="fa fa-bars"></span>
      </button>
       <!-- end: Mobile -->

    <!-- start: Javascript -->
    <script src="././public/asset/js/jquery.min.js"></script>
<!--    <script src="asset/js/jquery.ui.min.js"></script>-->
    <script src="././public/asset/js/bootstrap.min.js"></script>
    <script src="././public/asset/js/plugins/jquery.validate.min.js"></script>
    
     <script type="text/javascript">
      $(document).ready(function(){

    $("#signupForm").validate({
      errorElement: "em",
      errorPlacement: function(error, element) {
        $(element.parent("div").addClass("form-animate-error"));
        error.appendTo(element.parent("div"));
      },
      success: function(label) {
        $(label.parent("div").removeClass("form-animate-error"));
      },
      rules: {
        validate_firstname: "required",
        validate_lastname: "required",
        validate_username: {
          required: true,
          minlength: 2
        },
        validate_password: {
          required: true,
          minlength: 5
        },
        validate_confirm_password: {
          required: true,
          minlength: 5,
          equalTo: "#validate_password"
        },
        validate_email: {
          required: true,
          email: true
        },
        validate_agree: "required"
      },
      messages: {
        validate_firstname: "digita o seu nome",
        validate_lastname: "digita o seu nome",
        validate_username: {
          required: "digita o ultimo nome",
          minlength: "Your username must consist of at least 2 characters"
        },
        validate_password: {
          required: "Palavra passe",
          minlength: "Your password must be at least 5 characters long"
        },
        validate_confirm_password: {
          required: "confirma a palavra passe",
          minlength: "Your password must be at least 5 characters long",
          equalTo: "Please enter the same password as above"
        },
        validate_email: "digita email valido",
        validate_agree: "aceita os termos "
      }
    });

    // propose username by combining first- and lastname
    $("#username").focus(function() {
      var firstname = $("#firstname").val();
      var lastname = $("#lastname").val();
      if (firstname && lastname && !this.value) {
        this.value = firstname + "." + lastname;
      }
    });

    
   
    
  });
     </script>
  <!-- end: Javascript -->
  </body>
</html>






<?php

