<html lang="en" data-ng-app="pdc_app">
<head>
  <meta charset="utf-8">
  <meta name="description" content="Miminium Admin Template v.1">
  <meta name="author" content="Isna Nur Azis">
  <meta name="keyword" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>PDC-DCOS</title>

  <!-- start: Css -->
  <link rel="stylesheet" type="text/css" href="././publico/asset/css/bootstrap.min.css">

  <!-- plugins -->
  <link rel="stylesheet" type="text/css" href="././publico/asset/css/plugins/font-awesome.min.css"/>
  <link rel="stylesheet" type="text/css" href="././publico/asset/css/plugins/handsontable.full.min.css"/>
  <link rel="stylesheet" type="text/css" href="././publico/asset/css/plugins/animate.min.css"/>
  <link href="././publico/asset/css/style.css" rel="stylesheet">
  <!-- end: Css -->
 <script src="././bower_components/angular/angular.min.js"></script>
 <script src="app\app_js\ManController.js"></script>
  <link rel="shortcut icon" href="asset/img/logomi.png">
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
</head>

<body id="mimin" class="dashboard">
<!-- <ng-include src="'app/views/cabecario.phtml'"></ng-include>-->
<!-- start: Content -->
  <div class="navbar-default header navbar-fixed-top">
      
     <div class="panel box-shadow-none content-header ">
         
        
           <div class="navbar-header bg-blue"  style="width:100%;">
               
         <ul class="nav navbar-nav search-nav" id="container">
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ficheiro<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Criar Documento</a></li>
                 <li role="separator" class="divider"></li>
                  <li><a href="#">Abrir Documento</a></li>
                  <li role="separator" class="divider"></li>
                  <li > <div class="col-md-16"><input type="button" onclick="cli()" value="Guardar Document "></div> </li>
                  
                  <li role="separator" class="divider"></li>
                  <li><a href="#">Partilhar documento</a></li>
                </ul>
              </li>
                  
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Editar <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Cortar</a></li>
                 <li role="separator" class="divider"></li>
                  <li><a href="#">Copiar</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#">Colar</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#">Selecionar</a></li>
                </ul>
              </li>
              
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ver <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Editar</a></li>
                 <li role="separator" class="divider"></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#">Separated link</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
              
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Inserir <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Soma</a></li>
                 <li role="separator" class="divider"></li>
                  <li><a href="#">Subtração</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#">Outras</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#">#</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Formatar <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Editar</a></li>
                 <li role="separator" class="divider"></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#">Separated link</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
              </ul>
           </div>
         
     
        <div class="panel-body">
          <div class="col-md-12">
             
              
              
           <div class="header "  style="width:100%;">
               
         <ul class="nav nav-tabs " >
            
                <li >
                   <div class="fa-hover col-sm-3">  <a href="../icon/file-text-o"><h1> <i class="fa fa-file-text-o "></i>   </a></h1> </div> 
                
              </li>
              <li >
                  <div class="fa-hover  col-sm-3"><a href="../icon/folder-open-o"><h1><i class="fa fa-folder-open-o"></i></h1></a></div>
                
              </li>
              <li >
                  <div class="fa-hover  col-sm-3"><a href="../icon/floppy-o"> <h1><i class="fa fa-floppy-o"></i></h1> </a></div>
                
              </li>
              
              <li >
                  <div class="fa-hover  col-sm-3"><a href="../icon/file-pdf-o"><h1><i class="fa fa-file-pdf-o"></i></h1> </a></div>
                
              </li>
<!--              <li >
                  <div class="fa-hover  col-sm-3"><a href="../icon/print"><h1><i class="fa fa-print"></i> </h1></a></div>
                
              </li>-->
              
             
         </ul>
              </div>
              
<!--       A que vai alguma coisa       
              -->
             <div class="header "  style="width:100%;">
                  <div  class="col-md-12">
                      <form class="cmxform" id="signupForm" method="" action="">
                          <div class="col-md-2">
                          
                          <div class="input-group" >
                        <span class="input-group-addon"> <!-- aque vai algo --> </span>
                        <input type="text" class="form-control" aria-label="Amount (to the nearest dollar)">
                       
                       </div>
                                 
                           </div>
                           <div class="col-md-1">
                              <div class="input-group" >
                                  <button type="" class="btn btn-default"> <a href="../icon/superscript"> <strong><i class="fa fa-superscript"></i></a>  = </strong></button>
                       </div>
                           </div> 
                          <div class="col-md-6">
                          <div class="input-group" >
                         <input type="text" class="form-control" aria-label="Text input with multiple buttons">
                        <div class="input-group-btn">
                         
                          <button type="button" class="btn btn-default">OK</button>
                        </div>
                      </div>
                    
                      
                            </div>
                      </form>                                                                                      
                  </div>
             </div>
              
          </div>
        </div>
    </div>
    <div class="col-md-12 top-10 padding-0">
      <div class="col-md-12" >
        <div class="panel" ng-controller="recebeLinhaColuna">
<!--          <div class="panel-heading">
               
               a que vai algo 
              
          </div>-->
          <div >
              <div class="responsive-table" >
              <div id="pdc_tabela" ></div>
            </div>
             
        </div>
          
      </div>
    </div>
    </div>
  </div>
<!-- end: content -->

<script src="publico\asset\js\jquery.min.js"></script>
<script src="publico\asset\js\jquery.ui.min.js"></script>
<script src="publico\asset\js\bootstrap.min.js"></script>


<!-- plugins -->
<script src="publico\asset\js\plugins\moment.min.js"></script>
<script src="publico\asset\js\plugins\handsontable.full.min.js"></script>
<script src="bower_components\handsontable\dist\pikaday\pikaday.js"></script>
<script src="bower_components\handsontable\dist\ZeroClipboard\ZeroClipboard.js"></script>
<script src="bower_components\handsontable\dist\numbro\numbro.js"></script>
<!--<script src="././public/asset/js/plugins/jquery.nicescroll.js"></script>-->


<!-- custom -->
<script src="publico\asset\js\main.js"></script>
<script type="text/javascript">
    
//  $(document).ready(function () 

     $(function (){

  var 
   excel = document.getElementById('pdc_tabela'),
   linha = JSON.parse(window.sessionStorage.getItem('def_linha')),
   coluna=JSON.parse(window.sessionStorage.getItem('de_coluna')),
   cli,
//   salvar = document.getElementById('button[name=salvar]'),
   dado=[];
    
  

function firstRowRenderer(instance, td, row, col, prop, value, cellProperties) {
    Handsontable.renderers.TextRenderer.apply(this, arguments);
    td.style.fontWeight = 'bold';
    td.style.color = 'green';
    td.style.background = '#CEC';
    
  }
  
  
  var hot = new Handsontable(excel, {
    startRows:linha,
    startCols:coluna,
    colWidths: 80,
    rowHeights: 20,
     height: 370,
     minSpareRows: 1,
     colHeaders: function(coluna) {
          return coluna ;
                     },
    rowHeaders: true,
    stretchH: 'all',
    useFormula: true
   
    
  });
         // var $parent = document.getElementById('button[name=salvar]');
              cli=function(){
              $.ajax({
                url: 'salar.php',
                data: {data: hot.getData()}, // returns all cells' data
                dataType: 'json',
                type: 'POST',
                success: function (res) {
                  if (res.result === 'ok') {
                    alert('Data saved');
                  }
                  else {
                    alert('Save error');
                  }
                },
                error: function () {
                  alert('Save error');
                }
              });
            };


});



</script>
<!-- end: Javascript -->
</body>
</html>


<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

