


<!DOCTYPE html>
<html lang="en" data-ng-app="pdc_app" >
<head>

  <meta charset="utf-8">
  <meta name="keyword" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Login Pdc Docs</title>

  <!-- start: Css -->
  <link rel="stylesheet" type="text/css" href="././publico/asset/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="././publico/asset/css/plugins/icheck/skins/flat/aero.css"/> 
  <link href="././publico/asset/css/style.css" rel="stylesheet">
  <!-- end: Css -->

       <script src="bower_components\angular\angular.min.js"></script>
<!--        <script src="././bower_components/angular-route/angular-route.min.js"></script>-->
       <script src="app\app_js\ManController.js"></script>
  <link rel="shortcut icon" href="././public/asset/img/logomi.png">
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
    </head>

    <body id="mimin" class="dashboard boxed container padding-0"  >

        <div class="container" >
  
            <form  id="myLogin" class="form-signin" method="POST" action="login">
               
          <div class="panel periodic-login">
              <span class="atomic-number">    </span>
              <div class="panel-body text-center">
                  <h1 class="atomic-symbol">Pdc </h1>
                  <p class="atomic-mass">Docs</p>
                  <p class="element-name">Login Utilizador</p>

                  <i class="icons icon-arrow-down"></i>
                  <div class="form-group form-animate-text" style="margin-top:40px !important;">
                    <input type="text" id="nome" class="form-text" name="nome" required>
                    <span class="bar"></span>
                    <label>Username</label>
                  </div>
                  <div class="form-group form-animate-text" style="margin-top:40px !important;">
                    <input type="password" id="senha" class="form-text" name="senha" required>
                    <span class="bar"></span>
                    <label>Password</label>
                  </div>
                  <label class="pull-left">
                  <input type="checkbox" class="icheck pull-left" name="checkbox1"/> Lembra-me
                  </label>
<!--                  <input type="submit" class="btn col-md-12" ng-click="submit()" value="SignIn"/>-->
<!--                  <button type="button" class="btn col-md-12" ng-click="submit()"> Login user</button>-->
                  <input class="btn col-md-12" type="submit" value="Submit" >
              </div>
                <div class="text-center" style="padding:5px;">
                    <a href="forgotpass.html">Esqueceu a Password</a>
                    <a href="reg.html">| Registar-se</a> 
                </div>
          </div>
               
        </form>
  
            <span>
<!--                <tr>
            <tr ng-repeat="d in msg ">
            <td>{{ d.idusuario }}</td>
            <td>{{ d.nome }}</td>
            <td>{{ d.sobrenome }}</td>
            <td>{{ d.email }}</td>
            <td>{{ d.senha }}</td>
            <td>
            </tr>-->
            </span>
            
            
      </div>

      <!-- end: Content -->
      <!-- start: Javascript -->
      <script src="././publico/asset/js/jquery.min.js"></script>
      <script src="././publico/asset/js/jquery.ui.min.js"></script>
      <script src="././publico/asset/js/bootstrap.min.js"></script>
      <script src="././publico/asset/js/plugins/moment.min.js"></script>
      <script src="././publico/asset/js/plugins/icheck.min.js"></script>
     <script src="././publico/asset/js/plugins/jquery.nicescroll.js"></script>
      <!-- custom -->
      <script src="././public/asset/js/main.js"></script>
      <script type="text/javascript">
       $(document).ready(function(){
         $('input').iCheck({
          checkboxClass: 'icheckbox_flat-aero',
          radioClass: 'iradio_flat-aero'
        });
       });
     </script>
     
      
     
     
     
     <!-- end: Javascript -->
     
     
     
     
   </body>
   </html>



<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

