<!DOCTYPE html>
<html lang="en" data-ng-app="pdc_app">
<head>

  <meta charset="utf-8">
  <meta name="description" content="Miminium Admin Template v.1">
  <meta name="ismael" content="Isna Nur Azis">
  <meta name="keyword" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PDC_DOCS</title>

    <!-- start: Css -->
    <link rel="stylesheet" type="text/css" href="././publico/asset/css/bootstrap.min.css">

      <!-- plugins -->
      <link rel="stylesheet" type="text/css" href="././publico/asset/css/plugins/font-awesome.min.css"/>
      <link rel="stylesheet" type="text/css" href="././publico/asset/css/plugins/simple-line-icons.css"/>
<!--       <link rel="stylesheet" type="text/css" href="././public/asset/css/plugins/handsontable.full.min.css"/>-->
      <link rel="stylesheet" type="text/css" href="././publico/asset/css/plugins/animate.min.css"/>
      <link rel="stylesheet" type="text/css" href="././publico/asset/css/plugins/fullcalendar.min.css"/>
     <link href="././publico/asset/css/style.css" rel="stylesheet">
      
  <!-- end: Css -->
  
     <script src="././bower_components/angular/angular.min.js"></script>
     <script src="app\app_js\ManController.js"></script>
     <!--<script src="././bower_components/angular-route/angular-route.min.js"></script>-->
   <!--  
    <script src="././bower_components/handsontable/dist/handsontable.full.js"></script> 
    <script src="././bower_components/ngHandsontable/dist/ngHandsontable.js"></script>-->
<!--    <script src="././bower_components/ngHandsontable/demo/js/services/dataFactory.js"></script>-->
    
       
  <link rel="shortcut icon" href="././publico/asset/img/logomi.png">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

 <body id="mimin" class="dashboard boxed container padding-0">
      <!-- start: Header -->
       <nav class="navbar container navbar-default header navbar-fixed-top">
          <div class="col-md-12 nav-wrapper">
            <div class="navbar-header" style="width:100%;">
              <div class="opener-left-menu is-open">
                <span class="top"></span>
                <span class="middle"></span>
                <span class="bottom"></span>
              </div>
                <a href="index" class="navbar-brand">
                 <b>PDC-DOCS</b>
                </a>

              <ul class="nav navbar-nav search-nav">
                <li>
                   <div class="search">
                    <span class="fa fa-search icon-search" style="font-size:23px;"></span>
                    <div class="form-group form-animate-text">
                      <input type="text" class="form-text" required>
                      <span class="bar"></span>
                      <label class="label-search">pesquisar documento </label>
                    </div>
                  </div>
                </li>
              </ul>

              <ul class="nav navbar-nav navbar-right user-nav">
                <li class="user-name"><span>sofia filipe</span></li>
                  <li class="dropdown avatar-dropdown">
                   <img src="././publico/asset/img/avatar.jpg" class="img-circle avatar" alt="user name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"/>
                   <ul class="dropdown-menu user-dropdown">
                     <li><a href="#"><span class="fa fa-user"></span> Meu  Perfil</a></li>

                     <li role="separator" class="divider"></li>
                     <li class="more">
                      <ul>
                        <li><a href=""><span class="fa fa-cogs"></span></a></li>
                        <li><a href=""><span class="fa fa-lock"></span></a></li>
                        <li><a href=""><span class="fa fa-power-off "></span></a></li>
                      </ul>
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </nav>

      <!-- end: Header  a que  é a barra lateral -->

      <div class="container-fluid mimin-wrapper bg-light-grey">

          <!-- start:Left Menu -->
            <div id="left-menu">
              <div class="sub-left-menu scroll">
                <ul class="nav nav-list">
                    <li><div class="left-bg"></div></li>
                    <li class="time">
                      <h1 class="animated fadeInLeft">21:00</h1>
                      <p class="animated fadeInRight"> <!-- qualquer coisa--></p>
                    </li>
                    <li class="active ripple">
                      <a class="tree-toggle nav-header"><span class="fa-book fa"></span> Documentos
                        <span class="fa-angle-right fa right-arrow text-right"></span>
                      </a>
                      <ul class="nav nav-list tree">
                          <li role="presentation">
                              <a href="#tabs-demo7-area1" id="tabs-demo6-1" role="tab" data-toggle="tab" aria-expanded="true">Criar Documento</a></li>
                          
                              
                          <li>
                              <a href="#tabs-demo7-area7" role="tab" id="tabs-demo6-2" data-toggle="tab" aria-expanded="false">Abrir Documento</a></li>
                         
                              
                      </ul>
                    </li>
                    <li class="ripple">
                      <a class="tree-toggle nav-header">
                        <span class="fa-user fa"></span> Perfil
                        <span class="fa-angle-right fa right-arrow text-right"></span>
                      </a>
                      <ul class="nav nav-list tree">
                        <li> <a href="#tabs-demo7-area5" role="tab" id="tabs-demo6-5" data-toggle="tab" aria-expanded="false">Alterar Palavra-Passe</a></li>
                        <li><a href="#tabs-demo7-area6" role="tab" id="tabs-demo6-6" data-toggle="tab" aria-expanded="false">Eliminar Conta</a></li>
                      </ul>
                    </li>

                  </ul>


                </div>
            </div>
          <!-- end: Left Menu -->

          <!-- a que é o menu do meio da pagina-->
<div  id="content">
          <div class="col-md-12">
                  <div class="col-md-12">

                  <div class="col-md-12 tabs-area">

                    <ul id="tabs-demo6" class="nav nav-tabs nav-tabs-v6" role="tablist">
                        <li role="presentation" class="active"> 
                        <a href="#tabs-demo7-area1" id="tabs-demo6-1" role="tab" data-toggle="tab" aria-expanded="true">Criar Documento</a>
                      </li>
                      <li role="presentation" class="">
                        <a href="#tabs-demo7-area2" role="tab" id="tabs-demo6-2" data-toggle="tab" aria-expanded="false">Listar Documento</a>
                      </li>
                      <li role="presentation">
                        <a href="#tabs-demo7-area3" id="tabs-demo6-3" role="tab" data-toggle="tab" aria-expanded="false">Documentos Partilhado</a>
                      </li>
                      
                      
                      
                    </ul>
                      
                      
      <div id="tabsDemo6Content" class="tab-content tab-content-v6 col-md-12">
       <div role="tabpanel" class="tab-pane fade " id="tabs-demo7-area1" aria-labelledby="tabs-demo7-area1">
    <p>          
                    
                            <!-- formularia que vai cria a folha do excel com lkinha e coluna -->
       <div class="col-md-10" >
  <div class="col-md-4 panel">
<!--    <div class="col-md-12 panel-heading">
      <h4>Definir o tamanho da Celula</h4>
    </div>-->
    <div class="col-md-12 panel-body" style="padding-bottom:30px;" >
      <div class="col-md-12"> 
        <form class="cmxform" id="signupForm"  ng-submit="submit()" ng-controller="perfilDefinir">
          <div class="col-md-8"> 
            <div class="form-group form-animate-text" style="margin-top:40px !important;">
                <input type="text" class="form-text" id="validate_firstname"  ng-model="def_linha" required>
              <span class="bar"></span>
              <label>Digita o Numero de Linha</label>
            </div>

            <div class="form-group form-animate-text" style="margin-top:40px !important;">
                <input type="text" class="form-text" id="validate_username"  ng-model="def_coluna" required>
              <span class="bar"></span>
              <label>Digita o Numero de Coluna</label>
            </div>
          </div>

          <div class="col-md-12">

              <input class="submit btn btn-danger" type="submit" value="Submit">
        </div>
          
      </form>
               
    </div>
  </div>
</div>

</div>
   
                   </p>     
                      </div>
                        
                        
                         <!--A QUE  ÉONDE SERA LISTADA OS DOCUMENTOS  --> 
        <div role="tabpanel" class="tab-pane fade" id="tabs-demo7-area2" aria-labelledby="tabs-demo7-area2">
                          <p>
                           
  <div class="col-md-12 top-20 padding-0">
    <div class="col-md-12">
      <div class="panel">
<!--        <div class="panel-heading"><h3>Docunentos</h3></div>-->

        <div class="panel-body">
          <div class="responsive-table">
          <table id="datatables-example" class="table table-striped table-bordered" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Name</th>
              <th>Estado</th>
              <th>Data de Criação</th>
              <th>Abrir</th>
              <th>Comparilhar</th>
              <th>Eliminar</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Tiger Nixon</td>
              <td>System Architect</td>
              <td>Edinburgh</td>
              <td>
                  <div class="col-md-12">
                                   <button class="btn ripple btn-3d btn-primary">
                                      <div>
                                        <span>Abrir</span>
                                      </div>
                                       
                                    </button>   
                              </div>
              </td>
              <td>
                     <div class="col-md-12">
                                   <button class="btn ripple btn-3d btn-success">
                                      <div>
                                        <span>Editar</span>
                                      </div>
                                       
                                    </button>   
                              </div> </td>
              <td>
                   <div class="col-md-12">
                                   <button class="btn ripple btn-3d btn-danger">
                                      <div>
                                        <span>Deletar</span>
                                      </div>
                                     
                                    </button>   
                              </div> 
              </td>
            </tr>
            
            <tr>
              <td>Ashton Cox</td>
              <td>Junior Technical Author</td>
              <td>San Francisco</td>
              <td><div class="col-md-12">
                                   <button class="btn ripple btn-3d btn-primary">
                                      <div>
                                        <span>Abrir</span>
                                      </div>
                                       
                                    </button>   
                              </div></td>
              <td>
                            <div class="col-md-12">
                                   <button class="btn ripple btn-3d btn-success">
                                      <div>
                                        <span>Editar</span>
                                      </div>
                                       
                                    </button>   
                              </div> 
              </td>
              <td>
                              <div class="col-md-12">
                                   <button class="btn ripple btn-3d btn-danger">
                                      <div>
                                        <span>Deletar</span>
                                      </div>
                                     
                                    </button>   
                              </div> 
                  
              </td>
            </tr>
            <tr>
              <td>Cedric Kelly</td>
              <td>Senior Javascript Developer</td>
              <td>Edinburgh</td>
              <td><div class="col-md-12">
                                   <button class="btn ripple btn-3d btn-primary">
                                      <div>
                                        <span>Abrir</span>
                                      </div>
                                       
                                    </button>   
                              </div></td>
                 <td>
                  <div class="col-md-12">
                                   <button class="btn ripple btn-3d btn-success">
                                      <div>
                                        <span>Editar</span>
                                      </div>
                                       
                                    </button>   
                          </div> </td>
                    <td>
                  
                        <div class="col-md-12">
                                   <button class="btn ripple btn-3d btn-danger">
                                      <div>
                                        <span>Deletar</span>
                                      </div>
                                     
                                    </button>   
                            </div>
                 </td>
                    </tr>
            
          </tbody>
            </table>
          </div>
            
            
            
      </div>
    </div>
  </div>
  </div>             
        </p>
          </div>
                         
                      <div role="tabpanel" class="tab-pane fade" id="tabs-demo7-area3" aria-labelledby="tabs-demo7-area3">
                        <p> A que e onde vai ser mostrado os documentos compartilhado</p>
                      </div>
                      <div role="tabpanel" class="tab-pane fade" id="tabs-demo7-area4" aria-labelledby="tabs-demo7-area4">
                        <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
                      </div>
                         
                         
                       
                         
                <div role="tabpanel" class="tab-pane fade" id="tabs-demo7-area5" aria-labelledby="tabs-demo7-area5">
              <p> 
              <form class="form-signin">
              <div class="panel periodic-login" method="POST" action="alterar_password">
            
              <div class="panel-body text-center">
<!--                  <h1 class="atomic-symbol">Mi</h1>-->
              
<!--                  <p class="element-name">Miminium</p>-->

                  <i class="icons icon-arrow-down"></i>
                  <div class="form-group form-animate-text" style="margin-top:15px !important;">
                      <input type="password" class="form-text" name="passe_antiga" required>
                    <span class="bar"></span>
                    <label>Palavra-passe Antiga</label>
                    <p> </p>
                  </div>
                  <div class="form-group form-animate-text" style="margin-top:15px !important;">
                      <input type="password" class="form-text" name="nova_passe" required>
                    <span class="bar"></span>
                    <label>Nova Palavra-passe </label>
                    <p> </p>
                  </div> 
                 <div class="form-group form-animate-text" style="margin-top:15px !important;">
                    <input type="text" class="form-text" name="confirmar_passe"required>
                    <span class="bar"></span>
                    <label>Confirmar  Palavra-passe </label>
                    <p> </p>
                  </div>
                  <input type="submit" class="btn col-md-12" value="OK"/>
<!--                  <input type="submit" class="btn col-md-12" value="Reset"/>-->
              </div>
                
          </div>
        </form>
        </p>
              </div>
           <div role="tabpanel" class="tab-pane fade" id="tabs-demo7-area6" aria-labelledby="tabs-demo7-area6">
                        <p> Delfina......</p>
                      </div>                  
                       
                         
                         
                         
    <div role="tabpanel" class="tab-pane fade " id="tabs-demo7-area7" aria-labelledby="tabs-demo7-area1">
    <p>          
                    
                            <!-- formularia que vai cria a folha do excel com lkinha e coluna -->
       <div class="col-md-10" >
  <div class="col-md-4 panel">
<!--    <div class="col-md-12 panel-heading">
      <h4>Definir o tamanho da Celula</h4>
    </div>-->
    <div class="col-md-12 panel-body" style="padding-bottom:30px;" >
      <div class="col-md-12"> 
        <form class="cmxform" id="signupForm"  >
          <div class="col-md-8"> 
            <div class="form-group form-animate-text" style="margin-top:40px !important;">
                <input type="text" class="form-text" id="validate_firstname"  ng-model="def_linha" required>
              <span class="bar"></span>
              <label>Digita o Nome do Documento</label>
            </div>

            
          </div>

          <div class="col-md-12">

              <input class="submit btn btn-danger" type="submit" value="Submit">
        </div>
          
      </form>
               
    </div>
  </div>
</div>

</div>
   
                   </p>     
                      </div>                     
                         
                         
                         
                    </div>

                  </div>
                  </div>
              </div>
  </div>  
          <!-- start: content -->

          <!-- end: content -->
         
      </div>

      <!-- start: Mobile -->
      <div id="mimin-mobile" class="reverse">
        <div class="mimin-mobile-menu-list">
            <div class="col-md-12 sub-mimin-mobile-menu-list animated fadeInLeft">

              <ul class="nav nav-list">

                  <li class="active ripple">
                    <a class="tree-toggle nav-header"><span class="fa-home fa"></span> Documentos
                      <span class="fa-angle-right fa right-arrow text-right"></span>
                    </a>
                    <ul class="nav nav-list tree">
                        <li><a href="#">Cria Documento</a></li>
                        <li><a href="#">Listar Documento</a></li>
                        <li><a href="#">Documentos Partilhado</a></li>
                    </ul>
                  </li>
                  <li class="ripple">
                    <a class="tree-toggle nav-header">
                      <span class="fa-diamond fa"></span> Definição
                      <span class="fa-angle-right fa right-arrow text-right"></span>
                    </a>
                    <ul class="nav nav-list tree">
                      <li><a href="#">Top Navigation</a></li>
                      <li><a href="#">Boxed</a></li>
                    </ul>
                  </li>



                  <li class="ripple"><a class="tree-toggle nav-header"><span class="fa fa-envelope-o"></span> Notificação <span class="fa-angle-right fa right-arrow text-right"></span> </a>
                    <ul class="nav nav-list tree">
                      <li><a href="#">Inbox</a></li>
                      <li><a href="#">Compose Mail</a></li>
                      <li><a href="#">View Mail</a></li>
                    </ul>
                  </li>
                </ul>



            </div>
        </div>
      </div>
      <button id="mimin-mobile-menu-opener" class="animated rubberBand btn btn-circle btn-danger">
        <span class="fa fa-bars"></span>
      </button>
       <!-- end: Mobile -->

    <!-- start: Javascript -->
    <script src="././publico/asset/js/jquery.min.js"></script>
    <script src="././publico/asset/js/jquery.ui.min.js"></script>
    <script src="././publico/asset/js/bootstrap.min.js"></script>


    <!-- plugins -->
    <script src="././publico/asset/js/plugins/moment.min.js"></script>
    <script src="././publico/asset/js/plugins/fullcalendar.min.js"></script>
    
   
    <script src="././publico/asset/js/plugins/jquery.nicescroll.js"></script>
    <script src="././publico/asset/js/plugins/jquery.vmap.min.js"></script>
<!--    <script src="././public/asset/js/plugins/maps/jquery.vmap.world.js"></script>-->
    <script src="././publico/asset/js/plugins/jquery.vmap.sampledata.js"></script>
<!--    <script src="././public/asset/js/plugins/chart.min.js"></script>-->

<script src="././publico/asset/js/plugins/jquery.datatables.min.js"></script>
    <!-- custom -->
     <script src="././publico/asset/js/main.js"></script>
     

  <!-- end: Javascript -->
  </body>
</html>
