<!DOCTYPE html>
<html lang="en" data-ng-app="pdc_app">
<head>

  <meta charset="utf-8">
  <meta name="description" content="Miminium Admin Template v.1">
  <meta name="ismael" content="Isna Nur Azis">
  <meta name="keyword" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PDC_DOCS</title>

    <!-- start: Css -->
    <link rel="stylesheet" type="text/css" href="././publico/asset/css/bootstrap.min.css">

      <!-- plugins -->
      <link rel="stylesheet" type="text/css" href="././publico/asset/css/plugins/font-awesome.min.css"/>
      <link rel="stylesheet" type="text/css" href="././publico/asset/css/plugins/simple-line-icons.css"/>
<!--       <link rel="stylesheet" type="text/css" href="././public/asset/css/plugins/handsontable.full.min.css"/>-->
      <link rel="stylesheet" type="text/css" href="././publico/asset/css/plugins/animate.min.css"/>
      <link rel="stylesheet" type="text/css" href="././publico/asset/css/plugins/fullcalendar.min.css"/>
     <link href="././publico/asset/css/style.css" rel="stylesheet">
      
  <!-- end: Css -->
  
     <script src="././bower_components/angular/angular.min.js"></script>
     <script src="app\app_js\ManController.js"></script>
     <!--<script src="././bower_components/angular-route/angular-route.min.js"></script>-->
   <!--  
    <script src="././bower_components/handsontable/dist/handsontable.full.js"></script> 
    <script src="././bower_components/ngHandsontable/dist/ngHandsontable.js"></script>-->
<!--    <script src="././bower_components/ngHandsontable/demo/js/services/dataFactory.js"></script>-->
    
       
  <link rel="shortcut icon" href="././publico/asset/img/logomi.png">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

 <body id="mimin" class="dashboard boxed container padding-0">
      <!-- start: Header -->
       <nav class="navbar container navbar-default header navbar-fixed-top">
          <div class="col-md-12 nav-wrapper">
            <div class="navbar-header" style="width:100%;">
              <div class="opener-left-menu is-open">
                <span class="top"></span>
                <span class="middle"></span>
                <span class="bottom"></span>
              </div>
                <a href="index" class="navbar-brand">
                 <b>PDC-DOCS</b>
                </a>

              <ul class="nav navbar-nav search-nav">
                <li>
<!--                   <div class="search">
                    <span class="fa fa-search icon-search" style="font-size:23px;"></span>
                    <div class="form-group form-animate-text">
                      <input type="text" class="form-text" required>
                      <span class="bar"></span>
                      <label class="label-search">pesquisar documento </label>
                    </div>
                  </div>-->
                </li>
              </ul>

              <ul class="nav navbar-nav navbar-right user-nav">
                <li class="user-name"><span>Root usario</span></li>
                  <li class="dropdown avatar-dropdown">
                   <img src="././publico/asset/img/avatar.jpg" class="img-circle avatar" alt="user name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"/>
                   <ul class="dropdown-menu user-dropdown">
                     <li><a href="#"><span class="fa fa-user"></span> Meu  Perfil</a></li>

                     <li role="separator" class="divider"></li>
                     <li class="more">
                      <ul>
                        <li><a href=""><span class="fa fa-cogs"></span></a></li>
                        <li><a href=""><span class="fa fa-lock"></span></a></li>
                        <li><a href=""><span class="fa fa-power-off "></span></a></li>
                      </ul>
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </nav>

      <!-- end: Header -->

      <div class="container-fluid mimin-wrapper bg-light-grey">

          <!-- start:Left Menu -->
            
          <!-- end: Left Menu -->

          <div  id="container-fluid " style="margin-top: 38px;">
          <div class="col-md-12">
                  <div class="col-md-12">
                     <div class="col-md-12  bg-light-grey">
                      <div class="liner"></div>
                      <ul class="nav nav-tabs nav-tabs-v5" id="tabs-demo6">
                        <li class="active">
                         <a href="#tabs-demo6-area1" data-toggle="tab" title="home">
                          <span class="round-tabs one">
                            <i class="glyphicon glyphicon-home"></i>   
                          </span>
                        </a>
                      </li>

                      <li>
                        <a href="#tabs-demo6-area2" data-toggle="tab" title="Cadastrar Utilizador">
                         <span class="round-tabs two">
                           <i class="glyphicon glyphicon-user"></i>
                         </span>
                       </a>
                     </li>

                     <li>
                      <a href="#tabs-demo6-area3" data-toggle="tab" title="Documento">
                       <span class="round-tabs three">
                        <i class="glyphicon glyphicon-book"></i>
                      </span> </a>
                    </li>

<!--                    <li>
                      <a href="#tabs-demo6-area4" data-toggle="tab" title="Definação">
                       <span class="round-tabs four">
                         <i class="glyphicon glyphicon-globe"></i>
                       </span>
                     </a>
                   </li>-->

                   <li><a href="#tabs-demo6-area5" data-toggle="tab" title="Perfil do Utilizador">
                     <span class="round-tabs five">
                      <i class="glyphicon glyphicon-cog"></i>
                    </span> </a>
                  </li>
                </ul>
                <div class="tab-content tab-content-v5">
                  <div class="tab-pane fade in active" id="tabs-demo6-area1">

<!--                    <h3 class="head text-center">Custom Tabs<sup>™</sup> <span style="color:#f48250;">♥</span></h3>-->
                    <p class="narrow text-center">
                        
<!--                     tincidunt ut, utinam saperet facilisi an vim.-->
                    </p>

                    <p class="text-center">
                        
<!--                      <a href="" class="btn btn-success btn-round green"> start using Mimin <span style="margin-left:10px;" class="glyphicon glyphicon-send"></span></a>-->
                    </p>
                  </div>
                  <div class="tab-pane fade" id="tabs-demo6-area2">
                    <h3 class="head text-center">Definição do Utilizador</h3>
                    
                    
                    <p class="narrow text-center">
                      <!--- a que vai algumas definção --->
                    </p>

                    <p class="text-center">
                        
            <a href="#tabs-demo6-area6" class="btn btn-success btn-round green" data-toggle="tab" >  
              Adicionar Utilizador<span style="margin-left:10px;" class="glyphicon glyphicon-user"></span></a>
         
             <a href="#tabs-demo6-area8" data-toggle="tab" class="btn btn-primary btn-round green">
        Listar Utilizador<span style="margin-left:10px;" class="glyphicon glyphicon-hand-up"></span></a>           
                   
          <a href="#tabs-demo6-area7" data-toggle="tab" class="btn btn-danger btn-round green">
          Eliminar Utilizador<span style="margin-left:10px;" class="glyphicon glyphicon-user"></span></a>
                   
                    </p>

                      <p class="text-center">
                      
                    </p>
                  </div>
                  <div class="tab-pane fade" id="tabs-demo6-area3">
                    <h3 class="head text-center">Documentos Pessoais</h3>
<!--                    <p class="narrow text-center">
                      Lorem ipsum dolor sit amet, his ea mollis fabellas principes. Quo mazim facilis tincidunt ut, utinam saperet facilisi an vim.
                    </p>-->

                    <p class="text-center">
                      <a href="" class="btn btn-success btn-round green">
                          Criar Documento <span style="margin-left:10px;" class="glyphicon glyphicon-file"></span></a>
                   
                     <a href="" class="btn btn-primary btn-round primary">
                         Abrir Documento <span style="margin-left:10px;" class="glyphicon glyphicon-open"></span></a>
                      <a href="" class="btn btn-info btn-round info"> 
                          Listar Documento <span style="margin-left:10px;" class="glyphicon glyphicon-globe"></span></a>
                     <a href="" class="btn btn-raised btn-round green">
                         Documento Partilhado <span style="margin-left:10px;" class="glyphicon glyphicon-share"></span></a>
                    </p>
                  </div>
<!--                  <div class="tab-pane fade" id="tabs-demo6-area4">
                    <h3 class="head text-center">Drop comments!</h3>
                    <p class="narrow text-center">
                      Lorem ipsum dolor sit amet, his ea mollis fabellas principes. Quo mazim facilis tincidunt ut, utinam saperet facilisi an vim.
                    </p>

                    <p class="text-center">
                      <a href="" class="btn btn-success btn-round green"> start using Mimin <span style="margin-left:10px;" class="glyphicon glyphicon-send"></span></a>
                    </p>
                  </div>-->
                  <div class="tab-pane fade" id="tabs-demo6-area5">
                    <div class="text-center">
                      <i class="img-intro icon-checkmark-circle"></i>
                    </div>
                       <h3 class="head text-center">Informão Pessoal</h3>

                    <p class="narrow text-center">
                     <a href="" class="btn btn-primary btn-round green">Alterar Palavra-passe <span style="margin-left:10px;" class="glyphicon glyphicon-unchecked"></span></a>
                    <a href="" class="btn btn-danger btn-round green">Eliminar Conta <span style="margin-left:10px;" class="glyphicon glyphicon-remove"></span></a>
                  
                    </p>
                  </div>
         
                    
                    
    <div class="tab-pane fade" id="tabs-demo6-area6">
                        
<!--                    <div class="text-center">
                      <i class="img-intro icon-checkmark-circle"></i>
                    </div>-->
                        
<!--  <h3 class="head text-center">thanks for staying tuned! <span style="color:#f48250;">♥</span> Bootstrap</h3>-->
        <p class="narrow text-center">
                    
         <form class="form-signin">  
          <div class="panel periodic-login">
            
              <div class="panel-body text-center">
<!--                  <h1 class="atomic-symbol">Mi</h1>-->
              
<!--                  <p class="element-name">Miminium</p>-->

                  <i class="icons icon-arrow-down"></i>
                  <div class="form-group form-animate-text" style="margin-top:13px !important;">
                    <input type="text" class="form-text" required>
                    <span class="bar"></span>
                    <label>Nome completo</label>
                    <p> </p>
                  </div>
                  <div class="form-group form-animate-text" style="margin-top:13px !important;">
                    <input type="text" class="form-text" required>
                    <span class="bar"></span>
                    <label>Nome Utilizador </label>
                    <p> </p>
                  </div>
                 <div class="form-group form-animate-text" style="margin-top:13px !important;">
                    <input type="text" class="form-text" required>
                    <span class="bar"></span>
                    <label>Email</label>
                    <p> </p>
                  </div>
                  <div class="form-group " style="margin-top:13px !important;">
                      <label class="col-sm-10 control-label text-left "><h4>Seleciona Categoria </h4></label>
                        <select name="categoria"  class="form-control" >
                                        <option value="1"> Usuario Normal</option>
                                        <option value="2"> Usuario Root</option>
                                  </select>
                   
                    <p> </p>
                  </div>
                  <input type="submit" class="btn col-md-10" value="OK"/>
              </div>
                
          </div>
        </form>
          </p>      
          </div>  
               
            <div class="tab-pane fade" id="tabs-demo6-area7">
                    <div class="text-center">
                      <i class="img-intro icon-checkmark-circle"></i>
                    </div>
                   
                    <p class="narrow text-center">
                        <div class="responsive-table">
          <table id="datatables-example" class="table table-striped table-bordered" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Name</th>
              <th>Estado</th>
              <th>Eliminar</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Tiger Nixon</td>
              <td>System Architect</td>
             
              <td>
                   <div class="col-md-4">
                                   <button class="btn ripple btn-3d btn-danger">
                                      <div>
                                        <span>Deletar</span>
                                      </div>
                                     
                                    </button>   
                              </div> 
              </td>
            </tr>
            
            <tr>
              <td>Ashton Cox</td>
              <td>Junior Technical Author</td>
              
              <td>
                      <div class="col-md-4">
                                   <button class="btn ripple btn-3d btn-danger">
                                      <div>
                                        <span>Deletar</span>
                                      </div>
                                     
                                    </button>   
                       </div> 
                  
              </td>
            </tr>
            <tr>
              <td>Cedric Kelly</td>
              <td>Senior Javascript Developer</td>
              
                    <td>
                        <div class="col-md-4">
                                   <button class="btn ripple btn-3d btn-danger">
                                      <div>
                                        <span>Deletar</span>
                                      </div>
                                     
                                    </button>   
                            </div>
                 </td>
                    </tr>
            
          </tbody>
            </table>
          </div>
                    </p>
                  </div>                  
                    
              <div class="tab-pane fade" id="tabs-demo6-area8">
                    <div class="text-center">
                      <i class="img-intro icon-checkmark-circle"></i>
                    </div>
                 
                    <p class="narrow text-center">
                  listar utilizadores cadstrados
                    </p>
                  </div>   
              <div class="tab-pane fade" id="tabs-demo6-area9">
                    <div class="text-center">
                      <i class="img-intro icon-checkmark-circle"></i>
                    </div>
                 
                    <p class="narrow text-center">
                  listar utilizadores cadstrados
                    </p>
                  </div>  
<div class="tab-pane fade" id="tabs-demo6-area10">
                    <div class="text-center">
                      <i class="img-intro icon-checkmark-circle"></i>
                    </div>
                 
                    <p class="narrow text-center">
                  listar utilizadores cadstrados
                    </p>
                  </div>  
<div class="tab-pane fade" id="tabs-demo6-area11">
                    <div class="text-center">
                      <i class="img-intro icon-checkmark-circle"></i>
                    </div>
                 
                    <p class="narrow text-center">
                  listar utilizadores cadstrados
                    </p>
                  </div>  
<div class="tab-pane fade" id="tabs-demo6-area12">
                    <div class="text-center">
                      <i class="img-intro icon-checkmark-circle"></i>
                    </div>
                 
                    <p class="narrow text-center">
                  listar utilizadores cadstrados
                    </p>
                  </div>  
                    
            <div class="clearfix"></div>
         </div>
       </div>
                      
    </div>
   </div>
              
              
  </div>  
          
          
          <!-- start: content -->

          <!-- end: content -->

          
         
      </div>

      <!-- start: Mobile -->
      <div id="mimin-mobile" class="reverse">
        <div class="mimin-mobile-menu-list">
            <div class="col-md-12 sub-mimin-mobile-menu-list animated fadeInLeft">

              <ul class="nav nav-list">

                  <li class="active ripple">
                    <a class="tree-toggle nav-header"><span class="fa-home fa"></span> Documentos
                      <span class="fa-angle-right fa right-arrow text-right"></span>
                    </a>
                    <ul class="nav nav-list tree">
                        <li><a href="#">Cria Documento</a></li>
                        <li><a href="#">Listar Documento</a></li>
                        <li><a href="#">Documentos Partilhado</a></li>
                    </ul>
                  </li>
                  <li class="ripple">
                    <a class="tree-toggle nav-header">
                      <span class="fa-diamond fa"></span> Definição
                      <span class="fa-angle-right fa right-arrow text-right"></span>
                    </a>
                    <ul class="nav nav-list tree">
                      <li><a href="#">Top Navigation</a></li>
                      <li><a href="#">Boxed</a></li>
                    </ul>
                  </li>



                  <li class="ripple"><a class="tree-toggle nav-header"><span class="fa fa-envelope-o"></span> Notificação <span class="fa-angle-right fa right-arrow text-right"></span> </a>
                    <ul class="nav nav-list tree">
                      <li><a href="#">Inbox</a></li>
                      <li><a href="#">Compose Mail</a></li>
                      <li><a href="#">View Mail</a></li>
                    </ul>
                  </li>
                </ul>



            </div>
        </div>
      </div>
      <button id="mimin-mobile-menu-opener" class="animated rubberBand btn btn-circle btn-danger">
        <span class="fa fa-bars"></span>
      </button>
       <!-- end: Mobile -->

    <!-- start: Javascript -->
    <script src="././publico/asset/js/jquery.min.js"></script>
    <script src="././publico/asset/js/jquery.ui.min.js"></script>
    <script src="././publico/asset/js/bootstrap.min.js"></script>


    <!-- plugins -->
    <script src="././publico/asset/js/plugins/moment.min.js"></script>
    <script src="././publico/asset/js/plugins/fullcalendar.min.js"></script>
    
   
    <script src="././publico/asset/js/plugins/jquery.nicescroll.js"></script>
    <script src="././publico/asset/js/plugins/jquery.vmap.min.js"></script>
<!--    <script src="././public/asset/js/plugins/maps/jquery.vmap.world.js"></script>-->
    <script src="././publico/asset/js/plugins/jquery.vmap.sampledata.js"></script>
<!--    <script src="././public/asset/js/plugins/chart.min.js"></script>-->

<script src="././publico/asset/js/plugins/jquery.datatables.min.js"></script>
    <!-- custom -->
     <script src="././publico/asset/js/main.js"></script>
     

  <!-- end: Javascript -->
  </body>
</html>
